# serviceaccounts.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app1-service-a
  namespace: app1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app1-service-b
  namespace: app1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app2-service-a
  namespace: app2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app2-service-b
  namespace: app2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app3-service
  namespace: app3-frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app3-service
  namespace: app3-backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app4-web-service-a
  namespace: app4-web
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app4-web-service-b
  namespace: app4-web
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app4-api-service-a
  namespace: app4-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app4-api-service-b
  namespace: app4-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app4-api-service-c
  namespace: app4-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app4-db-service-a
  namespace: app4-db
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app4-db-service-b
  namespace: app4-db