# vault-auth-test-sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth-test
  namespace: vault
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth-test
  namespace: ldap
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth-ldap
  namespace: ldap
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth-db
  namespace: mysql
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth-api
  namespace: nginx
